### ISSUE TITLE
Not installing correctly on Mint 19

### ISSUE THREAD

**Issue by glicka** [steven-varga/h5cpp#13]
I tried following both the automatic instructions using `conan` and `cmake`, but neither one is installing correctly. Conan seems to work, but then when I try to import `h5cpp.h` in my code I get the error:
```
CMake Error at CMakeLists.txt:34 (find_package):
  By not providing "Findh5cpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "h5cpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "h5cpp" with any of
  the following names:

    h5cppConfig.cmake
    h5cpp-config.cmake

  Add the installation prefix of "h5cpp" to CMAKE_PREFIX_PATH or set
  "h5cpp_DIR" to a directory containing one of the above files.  If "h5cpp"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/glicka/GEANT/B4a/build/CMakeFiles/CMakeOutput.log".
```
And when I try to install `h5cpp` using `cmake` I get the error:
```
ERROR: boost_filesystem/1.65.1@bincrafters/stable: 'settings.compiler' value not defined
CMake Error at cmake/conan.cmake:322 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:399 (conan_cmake_install)
  CMakeLists.txt:21 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/home/glicka/h5cpp-0.1.0/build/CMakeFiles/CMakeOutput.log".
```
What do I need to do to get this to work?

**Comment by steven-varga** [comment]
Can you verify that you are posting on the right github page: as the sole author of H5CPP compiler assisted nonintrusive persistence for C++ I don't recall anything you posted above. No CMAKE support either. In fact it is a header only library; examples and performance tests driven by `make` and google test.

However if you're looking for a high performance library for machine learning that supports most linear algebra systems, arbitrary POD structs, comes with high performance stream recording you are on the right 'page'.
To [install H5CPP  clone this project](https://github.com/steven-varga/h5cpp.git), only need the headers if you don't use the compiler infrastructure and the [most recent version of HDF5 library](https://www.hdfgroup.org/downloads/hdf5/source-code/)  configured as 'serial':
```bash
./configure --prefix=/usr/local --enable-hl=no && make -j4 && sudo make install
```
then see examples how you can integrate H5CPP with your existing code or with your new ideas/implementation. If you have any trouble shoot me an email and I will walk you though.

best wishes:steven

**Comment by glicka** [comment]
I am sorry. I had 2 git repos open and posted my question to the wrong one. I am closing my issue because it does not belong here.
