### ISSUE TITLE
'after' example returns an error

### ISSUE THREAD

**Issue by gheber** [steven-varga/h5cpp#15]
```
./before
reading back data previously written:
        1 0.5 0.333333 0.25 0.2 0.166667 0.142857 0.125 0.111111 0.1
./after
terminate called after throwing an instance of 'h5::error::io::dataset::create'
  what():  /usr/local/include/h5cpp/H5capi.hpp line#  186 : couldn't create dataset...
```

**Comment by steven-varga** [comment]
Check if `generatet.h` has valid content. Be sure to update `h5cpp` compiler and try it again.

**Comment by gheber** [comment]
Just did a fresh clone. Rebuilt `h5cpp`. `generated.h` is "empty":
```
/* Copyright (c) 2018 vargaconsulting, Toronto,ON Canada
 *     Author: Varga, Steven <steven@vargaconsulting.ca>
 */
#ifndef H5CPP_GUARD_xmkOq
#define H5CPP_GUARD_xmkOq

#endif
```

**Comment by gheber** [comment]
What would be a simple `h5cpp` sanity check?

**Comment by steven-varga** [comment]
Unfortunately there are minor differences in LLVM system across distributions, it turns out that supporting all is not possible. On the bright side there are static linked [debian and RPM binary packages available on the project website](http://h5cpp.org/download)
