### ISSUE TITLE
'compound' example returns an error

### ISSUE THREAD

**Issue by gheber** [steven-varga/h5cpp#16]
```
h5cpp  struct.cpp -- -std=c++11  -I/usr/local/include -I/usr/local/h5cpp-llvm  -Dgenerated.h
H5CPP: Copyright (c) 2018     , VargaConsulting, Toronto,ON Canada
LLVM : Copyright (c) 2003-2010, University of Illinois at Urbana-Champaign.
g++ -o struct.o  -std=c++11  -I/usr/local/include -I/usr/local/h5cpp-llvm -c struct.cpp
g++ struct.o -lhdf5  -lz -ldl -lm -o struct
./struct
HDF5-DIAG: Error detected in HDF5 (1.11.4) thread 0:
  #000: H5D.c line 164 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5VLcallback.c line 1787 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1754 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 76 in H5VL__native_dataset_create(): not a datatype ID
    major: Invalid arguments to routine
    minor: Inappropriate type
terminate called after throwing an instance of 'h5::error::io::dataset::create'
  what():  /usr/local/include/h5cpp/H5capi.hpp line#  186 : couldn't create dataset...
```

**Comment by steven-varga** [comment]
Can you check the content of `generated.h`? It should have the compound type descriptor in it. It may be missing because syntax error in the original file or an older version of `h5cpp` compiler is used.

**Comment by steven-varga** [comment]
Something is not right there. In any event I brought back `test.h5cpp.org` your credentials are the same from summer. After pull request from github and recompiling h5cpp compiler everything works fine.

Can you check if the library is installed/updated in `/usr/local/include/h5cpp` ? the tests don't run from the ./ tree...
let me know...
December 28, 2018 8:23 PM, "Gerd Heber" <notifications@github.com (mailto:%22Gerd%20Heber%22%20<notifications@github.com>)> wrote:
	I'm working off the master branch. h5cpp (the compiler) builds just fine.

**Comment by gheber** [comment]
Yes, `/usr/local/include/h5cpp` is there and updated.

**Comment by steven-varga** [comment]
debian based package provided with cmake driven examples to detect available linear algebra libraries.
please [download and install packages from the project web site](http://h5cpp.org/download)
