### ISSUE TITLE
Can't compile 'packet-table' example

### ISSUE THREAD

**Issue by gheber** [steven-varga/h5cpp#17]
I have Eigen installed in `/usr/local/include/eigen3` but still get this error:
```
h5cpp  packettable.cpp -- -std=c++11  -I/usr/local/include -I/usr/local/h5cpp-llvm  -Dgenerated.h
H5CPP: Copyright (c) 2018     , VargaConsulting, Toronto,ON Canada
LLVM : Copyright (c) 2003-2010, University of Illinois at Urbana-Champaign.
g++ -o packettable.o  -std=c++11  -I/usr/local/include -I/usr/local/h5cpp-llvm -c packettable.cpp
packettable.cpp:7:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense> // must include Eigen before <h5cpp/core>
          ^~~~~~~~~~~~~
compilation terminated.
```
Not sure what's amiss.

**Comment by steven-varga** [comment]
Hi Gerd,

it is because your Eigen installation is different from the one I had. Check the content of /usr/local/include/eigen3 either make a symlink or just add the proper directive:
-I/usr/local/include/eigen3

hope it helps

December 28, 2018 3:58 PM, "Gerd Heber" <notifications@github.com (mailto:%22Gerd%20Heber%22%20<notifications@github.com>)> wrote:
	I have Eigen installed in /usr/local/include/eigen3 but still get this error: 

	h5cpp packettable.cpp -- -std=c++11 -I/usr/local/include -I/usr/local/h5cpp-llvm -Dgenerated.h H5CPP: Copyright (c) 2018 , VargaConsulting, Toronto,ON Canada LLVM : Copyright (c) 2003-2010, University of Illinois at Urbana-Champaign. g++ -o packettable.o -std=c++11 -I/usr/local/include -I/usr/local/h5cpp-llvm -c packettable.cpp packettable.cpp:7:10: fatal error: Eigen/Dense: No such file or directory #include <Eigen/Dense> // must include Eigen before <h5cpp/core> ^~~~~~~~~~~~~ compilation terminated.  

	Not sure what's amiss.

**Comment by gheber** [comment]
Got it. Now I get this:
```
g++ -o packettable.o  -std=c++11 -I/usr/include/eigen3 -I/usr/local/include -I/usr/local/h5cpp-llvm -c packettable.cpp
g++ packettable.o -lhdf5 -lhdf5_hl  -lz -ldl -lm -lblas -llapack -o packettable
./packettable
HDF5-DIAG: Error detected in HDF5 (1.11.4) thread 0:
  #000: H5D.c line 164 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5VLcallback.c line 1787 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1754 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 76 in H5VL__native_dataset_create(): not a datatype ID
    major: Invalid arguments to routine
    minor: Inappropriate type
ERROR:/usr/local/include/h5cpp/H5capi.hpp line#  186 : couldn't create dataset..
```

**Comment by steven-varga** [comment]
debian based package provided with cmake driven examples to detect available linear algebra libraries.
please [download and install packages from the project web site](http://h5cpp.org/download)
