### ISSUE TITLE
Request for Example of Creating Group

### ISSUE THREAD

**Issue by ChrisDrozdowski** [steven-varga/h5cpp#18]
Can an example be provided for creating a group, assigning attributes to that group, and assigning one or more datasets to the group? 

Perhaps I am missing something.

**Comment by steven-varga** [comment]
Hi Chris,

I am still running behind with Windows version. Can I have your changes under Canonical CLA added to a new windows branch? This CLA basically allows me to take full ownership of your modifications, in return I will credit you for the modifications you made. 

best: steve

Here is the copy:
	The Canonical contributor agreement was a Contributor License Agreement required by Canonical Ltd (https://en.wikipedia.org/wiki/Canonical_Ltd) for all contributions to many projects established by Canonical. 

	In it, the contributor assigned copyright to Canonical and at the same time Canonical gave the contributor "a world-wide, non-exclusive, royalty-free and perpetual right to use, copy, modify, communicate and make available to the public (including without limitation via the Internet) and distribute, in each case in an original or modified form, the Assigned Contributions as (they) wish."[30] (https://en.wikipedia.org/wiki/Contributor_License_Agreement#cite_note-main-30)[31] (https://en.wikipedia.org/wiki/Contributor_License_Agreement#cite_note-Agreement-31) 

	Canonical started Project Harmony "...to assist organisations which use contribution agreements by providing standardised variable templates with clear and concise explanations...."[32] (https://en.wikipedia.org/wiki/Contributor_License_Agreement#cite_note-32) 

	As of August 2011, Canonical is requesting contributions be licensed under a Harmony Contribution Licence Agreement, rather than the copyright being assigned to Canonical.[33] (https://en.wikipedia.org/wiki/Contributor_License_Agreement#cite_note-33) With the Harmony CLA, "the contributor gives Canonical a licence to use their contributions. The contributor continues to own the copyright in the contribution, with full rights to re-use, re-distribute, and continue modifying the contributed code, allowing them to also share that contribution with other projects."[6] (https://en.wikipedia.org/wiki/Contributor_License_Agreement#cite_note-canonical.com-6) 
April 20, 2019 8:08 AM, "Chris Drozdowski" <notifications@github.com (mailto:%22Chris%20Drozdowski%22%20<notifications@github.com>)> wrote:
	Can an example be provided for creating a group, assigning attributes to that group, and assigning one or more datasets to the group? 

	Perhaps I am missing something.

**Comment by ChrisDrozdowski** [comment]
Hi,

Attached is a zipped folder containing the files I modified. You can find
my modifications (along with brief comments) by searching for _WIN32 in the
files. See the end of this email for my CLA. I couldn't find a good,
general template for the Canonical CLA, so I adapted language from various
other CLAs to create a simple one giving you ALL rights. Is that acceptable?

Please note that the issues I addressed are those that Visual Studio 2017
has complained about for my current project. I don't know if other issues
may pop up but if they do, I will let you know.

I can't run your tests because I don't have the time to deal with Armadillo
on Windows or the Google testing framework you use.

I also have not attempted to compile using any other compilers than the
default one for Visual Studio 2017. Again, I just don't have the time right
now.

If you like, I can contribute a Windows version of your utf-8 example.

CLA
====

I, Chris Drozdowski, do hereby completely release to Steven Varga and Varga
Consulting, any past, current, or future copyright claims to the
contributions I provide to the H5CPP project.

Additionally, I, Chris Drozdowski, do hereby completely release to Steven
Varga and Varga Consulting any past, current, or future patent claims to
the contributions I provide to the H5CPP project.


Chris Drozdowski
336-416-1870
drozdowski.chris@gmail.com

**Comment by ChrisDrozdowski** [comment]
Hi,

I observed that you didn't incorporate my changes into the files in the
vs2017-windows branch.

Chris Drozdowski
336-416-1870
drozdowski.chris@gmail.com

**Comment by ChrisDrozdowski** [comment]
Hi,

Sorry about bothering you. I see that you changed the macro to _MSC_VER.

I created a pull request for strdup issue. I was too distracted and made a
mistake earlier.

Chris Drozdowski
336-416-1870
drozdowski.chris@gmail.com

**Comment by steven-varga** [comment]
Groups are not fully supported yet, on the bright side all `hid_t` types can be passed transparently to H5CPP calls by default.
This is an example to wrap a group `hid_t` to H5CPP RAII enabled id. Note that both of them are binary equivalent, the magic happens at compile time: 
`h5::gr_t group_id{ H5Gcreate( hid_t loc_id, const char *name, size_t size_hint )};`

In other words, if you are lacking some functionality in H5CPP, just use the CAPI calls. There is no difference between the two other then the easy syntax and optimised workflow between the two. 
here are the descriptors:
```cpp
namespace h5 {
     /*file:  */ fd_t 
     /*dataset:*/ ds_t 
     /*attrib:*/ at_t
     /*group:  */ gr_t 
     /*object:*/ ob_t
     /*space: */ sp_t 
    /*datatype:*/ dt_t
}
```
The packet table `h5::pt_t` is an exception as it has its own implementation, and is one way compatible with `h5::ds_t` dataset identifiers.
