### ISSUE TITLE
Issue reading dataset into std::vector<std::string> when testing "string" example

### ISSUE THREAD

**Issue by ChrisDrozdowski** [steven-varga/h5cpp#23]
Steven, please confirm whether or not you see this issue when compiling/running "string" example in Linux. Is this a general issue or only in VC++ that I should look into fixing for VC++.

**Issue: H5CPP cannot read a string dataset into `std::vector<std::string>`.**
Dev Environment: Visual Studio 2017 (141) compiling as x64 with Win 8.1 64-bit.

Issue was discovered and is reproducible while testing the "string" example project.

**Details:**
Writing `std::vector<std::string>` to a dataset works properly.

But reading the same dataset back into a `std::vector<std::string>` triggers a `std::bad_alloc` exception when iterating the returned vector.

If you read the dataset into a `std::vector<const char*>`, the dataset is read properly and iterates without exception.

However, using `std::vector<const char*>` won't compile because it can't get by:
`static_assert( utils::is_supported<T>, "error: " H5CPP_supported_elementary_types );`
in H5Dread.hpp, line 36.

Commenting out that line allows for compilation and successful execution.

The code below (essentially from string.cpp) is a working example.
```
// CHD !!! This is important for Windows!
#define H5_BUILT_AS_DYNAMIC_LIB

/* Copyright (c) 2018 vargaconsulting, Toronto,ON Canada
 * Author: Varga, Steven <steven@vargaconsulting.ca>
 */
#include <vector>
#include <string>

#include <h5cpp/all>

int main(){
	//RAII will close resource, noo need H5Fclose( any_longer ); 
	h5::fd_t fd = h5::create("example.h5",H5F_ACC_TRUNC);
	{
		// CHD: This works correctly.
		std::vector<std::string> vec = h5::utils::get_test_data<std::string>(20);
		h5::write(fd, "/strings.txt", vec);
	}
	{
		// CHD: This will result in a std::bad_alloc exception when the returned
		// std::vector<std::string> is iterated.
		//auto vec = h5::read<std::vector<std::string>>(fd, "strings.txt");
		//for( auto i : vec )
			//std::cout << i <<"\n";

		// CHD: This will return vector properly and will iterate properly.
		// But only if the utils::is_supported assert in H5Dread.hpp, line
		// 36 is commented out.
		auto vec = h5::read<std::vector<const char*>>(fd, "strings.txt");
		for( auto i : vec )
			std::cout << i <<"\n";
	}
}
```

**Comment by ChrisDrozdowski** [comment]
Upon further investigation, it seems that when attempting to read a dataset into a `std::vector<std:string>`...

The code below (H5Dread.hpp, lines 220-221):
```
T ref = impl::get<T>::ctor( count );
element_type *ptr = impl::data( ref );
```
sets ptr to `std::basic_string` because it calls the `data` function overload (H5Mstl.hpp, line 58) 
```
template <class T> inline T* data( std::vector<T>& ref ){
	return ref.data();
}
```
Then when call is made to code below (H5Dread.hpp, line 74), ptr is a `std::basic_string`:
```
H5CPP_CHECK_NZ( H5Dread(
		static_cast<hid_t>( ds ), static_cast<hid_t>(mem_type), static_cast<hid_t>(mem_space),
		static_cast<hid_t>(file_space),	static_cast<hid_t>(dxpl), ptr ), h5::error::io::dataset::read, h5::error::msg::read_dataset);
```
And it returns ptr as being size: 972273274768.

This seems to be the culprit.

**Comment by steven-varga** [comment]
Not quite. The mechanism is different from 'normal' C++ programming. As it appears there is no template specialisation for std::string. 
When implementing attributes I moved over a new generation of type mechanism/system -- with better properties -- and didn't add or commit std::string.  Give me a few days to fix it, I began working on it...
steve

**Comment by steven-varga** [comment]
Chris,
can you please modify the added variable length string support for your Windows setup and let me know if worked? if did send me a pull request for windows branch.

Variable length string support is re-added, however I will revisit this issue some other time to further improve on performance. Unfortunately adding code most likely not lead a real HPC solution, instead a study required to see if compressed, fixed width strings are viable solution for cross platform massive string datastore.
