### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by barcode** [steven-varga/h5cpp#26]
Since i am currently extending h5cpp in my fork and plan to make a pull request at some point, it would be useful to know the coding conventions for this project.

The best option would be to use a tool for reformatting (astyle, clang-tidy etc.).
This would make it much easier to collaborate and keep the same style throughout the project (this would improve readability and thus maintainability) since collaborators could configure their editor to apply the file.

**Comment by steven-varga** [comment]
And what is the reason behind your -- extension -- if I may ask?

July 16, 2019 2:22 AM, "Raphael Grimm" <notifications@github.com (mailto:%22Raphael%20Grimm%22%20<notifications@github.com>)> wrote:
	Since i am currently extending h5cpp in my fork and plan to make a pull request at some point, it would be useful to know the coding conventions for this project. 

	The best option would be to use a tool for reformatting (astyle, clang-tidy etc.).
This would make it much easier to collaborate and keep the same style throughout the project (this would improve readability and thus maintainability) since collaboraters could configure their editor to apply the file.

**Comment by barcode** [comment]
> And what is the reason behind your -- extension -- if I may ask? what is that you wish to add/improve upon? 

Mostly it is interface usability:

- Add a macro to generate glue code required for compound structs (This is an alternative to the `h5cpp-compiler`
- Allow more types to be added directly (e.g.: `h5::create<std::array<Eigen::Matrix4f[3], 2>`)

Currently this is still WIP.

> In any event I accept contributions under [The Canonical contributor agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement#Canonical) 

Fine with me.

> The coding style is somewhat un-dorthodox: must be dense, readable and its existence justified. yes, I am aware of reformatting.

I am just asking, because the formatting sometimes is inconsistent and is unfamiliar to me. (indention with tabs / with spaces, spaces around operators and sometimes none, etc.)
Automatic formatting would make it easier for me (and probably others looking at the library).

**Comment by steven-varga** [comment]
If you like macros you may want to roll back to a year old version. The templated type-system is cleaner. Compiler is optional, although the topological sort is hard to beat -- but with some finess one can produce equivalent code by hand. See the provided examples.
