### ISSUE TITLE
Amend README.md for vs2017-windows branch

### ISSUE THREAD

**Issue by ChrisDrozdowski** [steven-varga/h5cpp#28]
When porting h5cpp to Visual C++ in the `vs2017-windows` branch, I am _only_ adapting file source code files in the `h5cpp` directory. I am not adapting any other files from the master repo.

Perhaps a note to this effect should be added to the main `README.md` for the `vs2017-windows` branch.

Also, even though I have included MPI and Kita based h5cpp code in the `vs2017-windows` branch, perhaps we should note that those feature areas will _not_ work in a Windows environment.

If it is agreed upon, I'll be happy to provide a PR.

**Comment by steven-varga** [comment]
That is correct, for now the goal is to know if it works. Personally I would leave MPI and KITA out as it can be confusing for people who don't know the details between OS-s. Knowing that it works for you will allow me to revisit this branch with confidence. 
Currently if asked of windows I redirect everyone to this branch and your work -- with the comment: 'known to work'.

**Comment by ChrisDrozdowski** [comment]
So you would like me to remove your KITA and MPI code from the branch entirely or just leave it in place? Your KITA and MPI code itself seems not to cause any issues to leave in place based on my current utilization of the branch. Of course, it will not work in VC++ nor would I even try to use it.

**Comment by steven-varga** [comment]
My apologies for the confusion: you are correct leaving it in. If ever becomes a problem will address it.
