### ISSUE TITLE
Repo for H5CPP MSVC Specific Examples

### ISSUE THREAD

**Issue by ChrisDrozdowski** [steven-varga/h5cpp#29]
Steven,

I created a separate repo for the MSVC specific H5CPP examples I've adapted:
https://github.com/ChrisDrozdowski/h5cpp-msvc-examples

I created it because it is essentially different than the structure of the H5CPP repo and I don't want to mix in Visual studio-specific files such a solution or project files.

Please let me know if you have any issues with this.

**Comment by steven-varga** [comment]
Hey Chris,
it works for me... at some later point of  the year we can take a look if we can and want to merge it. Thanks for your efforts!
