### ISSUE TITLE
Packet Table Behavior When Appending Vector

### ISSUE THREAD

**Issue by ChrisDrozdowski** [steven-varga/h5cpp#35]
I want to confirm whether this is expected behavior or not for packet table functionality.

When appending a vector to `h5:pt_t` and size of vector != chunk size, an exception is thrown.

(This occurs with my MSVC code- does it happen with Linux???)

Example code:
```
#include <h5cpp/all>
#include <cstddef>
#include <vector>

int main(){

	const size_t count = 2048; // Some arbitrary length not known at compile time.

	std::vector<double> data(count);
	for (std::size_t i = 0; i < count; ++i) { data[i] = i * 0.123; }

	const std::size_t chunk_size = 1024;

	try
	{
		h5::fd_t fd = h5::create("pt1.h5", H5F_ACC_TRUNC);
		h5::pt_t pt = h5::create<double>(fd, "some_path", h5::max_dims{ H5S_UNLIMITED },
			h5::create_path | h5::utf8, h5::chunk{ chunk_size } | h5::fill_value<double>(0));

		h5::append(pt, data); // Exception is thrown in this call.
	}
	catch (const std::exception& e)
	{
		std::cout << e.what() << std::endl;
	}
}
```

**Comment by steven-varga** [comment]
You are pushing some vector on to a vector (rank 1) shape? Can I ask what justifies this?
Shouldn't you be pushing a vector to a matrix or rank 2 shape?


Here is the section that restricts data pushed to chunk size. The rational behind this is that you have an underlying matrix or cube that you are filling row by row. HDF5 chunked dataset doesn't see smaller size at the edges. Instead there is a code path that does the fill for you. Not aligning to chunk size will result in reduced bandwidth. `h5::append` doesn't allow you to do that, instead it works with raw chunks, taking the underlying filesystem to its limits.

This code path was designed to record live video/audio streams or incoming blocked data from sensor network, optimised for maximum thoughput.  
```cpp
template<class T> inline typename std::enable_if< !h5::impl::is_scalar<T>::value,
void>::type h5::pt_t::append( const T& ref ) try {
...
   switch( dims_.size() ){
      case 1: // vector
	if( dims[0] * element_size == block_size )
		pipeline.write_chunk(offset, block_size, (void*) ptr_ );
	else throw h5::error::io::packet_table::write(
		H5CPP_ERROR_MSG("dimension mismatch: "
			+ std::to_string( dims[0] * element_size) + " != " + std::to_string(block_size) ));
   ...
}
...
}
```

If you have a single stream coming from a sensor network then let `h5::append` do the work for you. It fills in internal bucket to brim, then dumps it directly into dataset. Here is the code path:
```cpp
template<class T> inline typename std::enable_if< h5::impl::is_scalar<T>::value && !std::is_pointer<T>::value,
void>::type h5::pt_t::append( const T& ref ) try {
//SCALAR: store inbound data directly in pipeline cache
   static_cast<T*>( ptr )[n++] = ref;
   if( n != N ) return;
   n = 0;
   *offset = *current_dims;
   *current_dims += *chunk_dims;
   h5::set_extent(ds, current_dims);
   pipeline.write_chunk(offset,block_size,ptr);
} catch( const std::runtime_error& err ){
	throw h5::error::io::dataset::append( err.what() );
}
```

**Comment by ChrisDrozdowski** [comment]
The reason I use rank 1 shape rather than matrix (multi-rank) is because I am converting a 3rd party binary file into HDF5 file. The 3rd party file is comprised one or more (usually more) arbitrary length 1D double type arrays. Hence it makes sense to generate rank 1 datasets. _Oh, it'd be nice to do something more interesting :)_

The files aren't so big. 95% of the time the total data in the whole file is well under 500MB.

I was generating a vector by iterating through an individual 3rd party 1D array (I have to iterate due to 3rd party API- no access directly to the array as a whole).

Originally I wrote the vector to a `ds_t` but wanted to see if I could improve performance with packet tables. Not being familiar with them, I did some testing and discovered the behavior I mention in this issue.

Now it is clear that appending a vector to `pt_t` isn't the way to go _in my very particular case_. I understand the reasoning now and that is okay.

But based on a bit of testing, it seems I can skip generating the vector and simply append the values one by one to a `pt_t` during the iteration. This increases performance quite a bit and saves a good amount of memory.

I hope this helps explain

**Comment by steven-varga** [comment]
The only way you can make it faster if you are reading from an existing buffer, then break it into chunk size; then push the chunk onto the dataset with `h5::append`.  This is a zero copy operation resulting in  maximum performance.

In some other cases you may want to preserve the shape. This is called ragged or variable length arrays and currently not supported. 
best: steve
