### ISSUE TITLE
What is the status of and where is this project heading

### ISSUE THREAD

**Issue by kayarre** [steven-varga/h5cpp#39]
This seems like a really great tool and would like to be a user,  however I am wondering what the future of this project will be in terms of vision and timing. It sounds like maybe this is on the development back burner due to other exigencies or funding. If there is a better forum for this I am happy to move this somewhere else. I am mostly curious where it's going or could go.

**Comment by steven-varga** [comment]
Thank you for the interest.

The target is to provide general, seamless persistence for modern C++. In the next release  will  support sparse matrices, STL like objects including the full standard template library, and will come with  [improved documentation](http://sandbox.h5cpp.org). 
A later release will have extended compiler assistance paving the road for arbitrary object persistence, and possibly improved cross platform support.

In addition to 'regular' features there is much thought put into performance, MPI parallelism and filtering pipline.  However most of the work is **not coding related**. To give you an example: Sparse matrices have been handled various ways across platforms, to add complexity the HDFGroup based on FNAL study will be adding CAPI supported format. To coordinate and leverage the differences requires detailed understanding of the problem. 

As for the 'back burner':  I am financing this project from my own pocket, therefore there is priority to components my clients need. 
Other than my own research and coding time The HDFGroup sponsored the [ISC'19 BOF](http://isc19.h5cpp.org/) presentation, and [Chicgago '18 C++](http://chicago.h5cpp.org) user group presentation; and a webinar.  I am thankful for the effort Gerd Heber put into as liaison/advisor and Elena Pourmal organising the HDF5 C++ usergroup meetings,  David Pearah then CEO of HDFGroup being receptive to the idea. 

If you are an organisation that would benefit from a cross platform HPC capable general, seamless persistence for modern C++ and interested in funding the project please get in touch.

steve

**Comment by kayarre** [comment]
@steven-varga thank you for this explanation, this is great feedback.
