### ISSUE TITLE
= operator overload in H5Dappend.hpp missing return statement

### ISSUE THREAD

**Issue by ChrisDrozdowski** [steven-varga/h5cpp#46]
Return statement missing from = operator overload in H5Dappend.hpp (lines 26-28):
```
pt_t& operator=( h5::pt_t&& pt ){
    init(pt.ds);
}
```

**Comment by steven-varga** [comment]
Thanks Chris! 
see commit e18cdef2696f253a4bd99274938b68309f6c51fa
