### ISSUE TITLE
h5cpp dumps core w/ before-after, compound, and packet-table 

### ISSUE THREAD

**Issue by gheber** [steven-varga/h5cpp#5]
Check this out.

**Comment by steven-varga** [comment]
Hey Gerd,
on ubuntu@master.vargaconsulting.ca there is a minimum system installed for ubuntu-18.04LTS with using only ubuntu packages wherever possible: gcc-7, libhdf5-serial-dev 1.10.0-patch1+docs-4 and your llvm setup with a newly created h5cpp branch: ubuntu-18.04LTS. 
I was able to reproduce the coredump, in addition to there are errors possibly related to hdf5 library versioning.

steve

**Comment by steven-varga** [comment]
**problem**: broken LLVM, use LLVM + clang compiled from source as outlined
