### ISSUE TITLE
Update Links to New Repo for Windows Port of H5CPP

### ISSUE THREAD

**Issue by ChrisDrozdowski** [steven-varga/h5cpp#54]
Hi,

I created a new repo for the Windows port of H5CPP. It is here:
https://github.com/ChrisDrozdowski/h5cpp-windows

Please modify links to the old repos on this to reflect the new repo.

My rationale is that it puts the h5cpp source and examples in one unified repo. I also included the source for Armadillo and Eigen so that the examples can be compiled out of box with minimal work.

I will be maintaining this repo as the Windows port from now on.

**Comment by steven-varga** [comment]
yes of course; will refer every windows users to the new link.
