### ISSUE TITLE
extend supported stl types for std::array

### ISSUE THREAD

**Issue by nevion** [steven-varga/h5cpp#55]
I think I see 2 spaces where std::array should be incorporated

The first is in simply writing or reading std::array<T, N> to a dataset/attribute.

The second is writing a collection of std::array<T, N>, like std::vector<std::array<T, N>>

**Comment by steven-varga** [comment]
Next version will have native STL support, until then you can obtain the pointer to `std::array` with `data()` then use [`h5::write`](http://sandbox.h5cpp.org/architecture/#write) template for typed pointers, with the [correct/desired dimensions](http://sandbox.h5cpp.org/architecture/#data-space-and-dimensions)
```
[...]
std::array<double,5> my_data = {1,2,3,4,5};
h5::write("my_file.h5", "my_dataset", my_array.data(), 
   h5::max_dims{30,40,50}, // maximum size of file space
   h5::count{5,1,1},       // size of memory space
   h5::offset{5,0,0});     // the start of location/coordinates in file space  
```
`std::vector<std::array<T, N>>` is a bit trickier, as of now can only be done if you know details of the HDF5 format, ragged arrays in particular. In any event this will be and many more combinations in the upcoming version. [Here is the list of objects ](http://sandbox.h5cpp.org/typesystem/#objects-and-type-classification).

**Comment by nevion** [comment]
Hmm, ess's h5cpp ( as well as my old dead project) did this pretty easily, re the std::vector handler, you just need to recursively construct the type T's h5 type; no need to bring in the dreaded vlen: https://github.com/ess-dmsc/h5cpp/blob/2cfb0adae60d847f95d692374df5a69732c2c0e2/src/h5cpp/datatype/type_trait.hpp#L217

**Comment by steven-varga** [comment]
yes you are correct, the particular type is indeed a standard layout, the std::array<std::vector<T>,N) and similar variants fall under VLEN category. The types are 'reasoned' as opposed to 'baked in'.
