### ISSUE TITLE
Eigen simplification (almost-patch)

### ISSUE THREAD

**Issue by eudoxos** [steven-varga/h5cpp#61]
I simplified most of the code in `H5Meigen.hpp` by using Eigen [base types](http://eigen.tuxfamily.org/dox/TopicClassHierarchy.html).

There are 4 parts: `size`, `data`, `get` and `decay`.

For `size`, `data`, it is straightforward to write the function like this (handles all of `Matrix` and `Array`, bot row-major and column-major):

```
template<class T>
typename T::Scalar* data(const ::Eigen::PlainObjectBase<T>& ref ){
		return const_cast<typename T::Scalar*>( ref.data() );
}
template<class T>
inline std::array<size_t,2> size( const ::Eigen::PlainObjectBase<T>& ref){
	if constexpr(T::IsRowMajor) return {(hsize_t)ref.rows(),(hsize_t)ref.cols()};
	return {(hsize_t)ref.cols(),(hsize_t)ref.rows()};
}
```
The others are not as straightforward, as they are class templates (which are matched differently than function templates, like `data` and `size` — those use overload resolution).

For `get`, I had to change the base template in H5Mstl.hpp, adding `typename = void`:
```
template <class T, typename = void> struct get {
   	static inline T ctor( std::array<size_t,impl::rank<T>::value> dims ){
		return T(); }};
```
 so that the Eigen template is then more specialized:
```
template<class T>
struct get<T,std::enable_if_t<std::is_base_of_v<Eigen::PlainObjectBase<T>,T>>>{
	static inline T ctor( std::array<size_t,2> dims ){
		if constexpr(T::IsRowMajor) return T( dims[0], dims[1] );
		return T( dims[1], dims[0] );
}};
```
Finally, for `decay`, I could not use the extra parameter trick as `decay` is declared with ellipsis `template <T, ...>`, so no solution for that one so far.

What do you think? Would this be worth putting as a pull request?

---

Incidentally, I was checking out HighFive recently (they use too much whitespace in the code for my taste, though ;) ) and was helping there with a similar issue. The most elegant solution seemed to be to put all such common functions into a class template, one for each supported array types (one has to write the type-matching code only once, for the whole class).

An example is here: https://gist.github.com/eudoxos/43f11cfb04d33b4f3e5cf309ad628365 : `io_impl` is specialized for each supported array type, containing all the functions. For h5cpp, those 4 would be obviously `decay`, `data`, `size` and `ctor` and they would be called as (e.g.) `h5::impl::support<T>::decay` rather than `h5::impl::decay<T>` and so on.

**Comment by steven-varga** [comment]
Please notice that submitting code requires you signing a [Canonical CLA](https://ubuntu.com/legal/contributors)

> What do you think?

What feature this code snippet introduces that the existing doesn't? How do you use this feature? Reading someone else's code and possibly -- not by purpose, rather just by accident -- inserting into this code leads to tainting. Even if you signed a CLA it will not prevent me from being sued / criticised :( . 

Other than that,  I think it is very proactive of you. However  please notice that you are working on a old code base, the current master  branch will be eventually replaced with the dev branch which has more accommodating type system.

When you have time, let's get on the phone, I have a different library, which I am open sourcing and needs active contributors :) Also will have a larger audience and better general exposure. I think you would like it.

**Comment by eudoxos** [comment]
Okay, good, I will check the dev branch first and will close this one :)
