### ISSUE TITLE
Read single std::string attribute?

### ISSUE THREAD

**Issue by spinicist** [steven-varga/h5cpp#62]
Hello,

Looking at https://github.com/steven-varga/h5cpp/blob/master/examples/attributes/attributes.cpp it appears that string array attributes (`std::aread<std::vector<std::string>>`) is supported. However, I can't find an example for only a single string, i.e. `std::aread<std::string>`, and indeed, this fails to compile. Is this not supported? Is there a way to read a single string/char* attribute into a std::string?

Thanks in advance!

**Comment by steven-varga** [comment]
Thanks for reporting! can you please try again: 
```
std::cout << "att_07 : "; std::string att_07 = h5::aread<std::string>(ds,"att_07");
		std::cout << att_07  <<"\n";
```
in commit 9b9b90c
best wishes: steve

**Comment by spinicist** [comment]
Hello,

That now compiles. However, the following snippet is failing to compile:

```
Eigen::MatrixXf blah(10, 20);
h5::write(file, "/test", blah);
```

with the following error:

```
[build] ../external/h5cpp/h5cpp/H5Dwrite.hpp:166:23: error: no matching function for call to 'size'
[build]                 h5::count_t count = impl::size( ref );
[build]                                     ^~~~~~~~~~
```

Should I open a new issue?

**Comment by spinicist** [comment]
Ah. I see the problem with Eigen. I did not have `#include <Eigen/Dense>` _before_ `#include <h5cpp/all>`, and hence the `#define` to enable Eigen was not in place.

I think this needs to be documented explicitly, or perhaps the `#ifdefine` for Eigen removed and users have to include <h5cpp/H5eigen.hpp> explicitly. Relying on the include order is sub-optimal, particularly given that `.clang-format` will re-order includes.

**Comment by steven-varga** [comment]
Thanks for the suggestions. Did you [try reading the relevant examples?](https://github.com/steven-varga/h5cpp/blob/master/examples/linalg/eigen3.cpp) On my version it clearly reads:
```
#include <iostream>
#include <Eigen/Dense> // must include Eigen before <h5cpp/core>
#include <h5cpp/all>
```
 AFAIK we know there is no problem with Eigen, it works as advertised.

**Comment by spinicist** [comment]
Yes, I did read the Eigen examples (and most of the others). I completely missed that comment.

I'm not disputing that this was user error. But I'm going to blame the compiler as well as the obtuse messages they generate from C++ SFINAE methods make diagnosing these errors tiresome.

**Comment by steven-varga** [comment]
I 'have closed this issue to prevent escalation.  This is a public forum, please follow 'be nice policy: don't blame others, thanks you for your understanding. Please do not reopen this thread for other reason than  `std::string` attribute doesn't work.
