### ISSUE TITLE
Packet table flush fails with one element in cache.

### ISSUE THREAD

**Issue by m-chichikalov** [steven-varga/h5cpp#64]
Hi Steven, good piece of obstruction; I really like this wrapper for hdf5.

The next code
``` c++
h5::pt_t pt = h5::create<mc:sometype_t>(fd, getDataSetName(),
	h5::max_dims{ H5S_UNLIMITED }, h5::chunk{ 1000 } | h5::gzip{9} );
std::cout << pt;
h5::append( pt, sample );
pt.flush();
std::cout << pt;
```

will generate output
```
packet table:
------------------------------------------
rank: 1 N:1000 n:0
element size: 24 block size: 24000
current dims: [0]
chunk dims: [0]
offset : [0] count : [1]
ds: 360287970189639680 dxpl: 720575940379279425
fill value: 0x562efb0632a0 buffer: 0x562efb076f00

HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: H5Dio.c line 400 in H5Dwrite_chunk(): failure to copy offset array
    major: Dataset
    minor: Can't allocate space
  #001: H5Dio.c line 120 in H5D__get_offset_copy(): offset doesn't fall on chunks's boundary
    major: Dataspace
    minor: Inappropriate type

packet table:
------------------------------------------
rank: 1 N:3e8 n:1
element size: 18 block size: 5dc0
current dims: [1]
chunk dims: [1]
offset : [0] count : [1]
ds: 500000000000000 dxpl: a00000000000041
fill value: 0x562efb0632a0 buffer: 0x562efb076f00
```

I almost didn't work with hdf5 before, is it some kind of limitation of packet tables or a bug.
I can spend some time to fix it if you give me some clues.

This is not common case to flush chunk with only one element, but I have a system where I don't have constant sample rate and flushing and moving to other table on a timeframe base, so quite possible. 

Regards,
Max 73!

**Comment by m-chichikalov** [comment]
Observing quite similar behavior during attempt to append samples into previously created and opened h5::pt_t

``` c++
{
    h5::fd_t fd = h5::open( "example.h5", H5F_ACC_RDWR );
    h5::pt_t pt = h5::open( fd, "test_0");

    std::cout << pt;

    h5::append( pt, data );
    h5::append( pt, data );
    h5::append( pt, data );
    h5::append( pt, data );

    std::cout << pt;
}
```

output

```
packet table:
------------------------------------------
rank: 1 N:1000 n:0
element size: 24 block size: 24000
current dims: [52]
chunk dims: [52]
offset : [0] count : [1]
ds: 360287970189639680 dxpl: 720575940379279429
fill value: 0x55e4a4973350 buffer: 0x55e4a497d280

packet table:
------------------------------------------
rank: 1 N:3e8 n:4
element size: 18 block size: 5dc0
current dims: [34]
chunk dims: [34]
offset : [0] count : [1]
ds: 500000000000000 dxpl: a00000000000045
fill value: 0x55e4a4973350 buffer: 0x55e4a497d280

HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: H5Dio.c line 400 in H5Dwrite_chunk(): failure to copy offset array
    major: Dataset
    minor: Can't allocate space
  #001: H5Dio.c line 120 in H5D__get_offset_copy(): offset doesn't fall on chunks's boundary
    major: Dataspace
    minor: Inappropriate type
```

I think the issue is not correctly initialized `n`, is it?

**Comment by steven-varga** [comment]
Hi Max, the only problem here that needs fixing is to hide `flush` from peering eyes :) Luckily the [documentation](http://sandbox.h5cpp.org/architecture/#append) doesn't have anything to do with this.
```
h5::append( pt, sample );
pt.flush();  // <-- this is an internal/undocumented call, will be removed
// from next version, to prevent wrong pattern; it's only purpose is to 
// flush the packet table pipeline caches. WILL NOT FLUSH
// HDF5 internal caches!!!
```
I checked out the implementation with your code, without the undocumented `flush` call and worked fine.
As I understand you are trying to do something, perhaps increase 'reliability' by flushing caches on each call? is this related the ACID property I see popping up on the HDF5 forum? -- in any event: this is not the right place... and this `flush` is not [`H5Fflush`](https://support.hdfgroup.org/HDF5/doc1.8/RM/RM_H5F.html#File-Flush)

`h5::append` by default has it's own pipeline, even if you flushed it it doesn't flush any caches of the underlying HDF5 system. 
On the bright side you could roll your own append. It will not perform very well -- but hey, you know what you are doing:
```
auto ds = h5::create(fd, "dataset_name", h5::max_dims{ H5S_UNLIMITED }, h5::chunk{ 1000 } | h5::gzip{9});
bool ever = true;

for(h5::current_dims dims = ...; ever;  inc(dims)){
     h5::set_extent(ds, dims);
     h5::write(ds, sample, ... );
     H5Fflush(ds, H5F_SCOPE_LOCAL);
}
```
The above code is safe to use, as it indeed does what you probably are upto. 

best, steve

**Comment by steven-varga** [comment]
As a second thought: I did put an `h5::flush` into API. oopsi... I didn't quite think the above through --- had a tough and long day --: my apologies...!   I don't quite know what exactly you want to do -- it does appear you want some sort of insurance the packet it on the disk.

If this is the case, flushing the append cache will not do, but I can add the H5Fflush to  `h5::flush(...)`. You still will have OS level caching, but if this works for you than I don't see a reason why not.
In this case there indeed is a bug, which needs a fix.

**Comment by steven-varga** [comment]
So I looked into this: Each chunk is either full or not, the ones which are not -- and get flushed, need to be compressed, then read back, decompressed and a new record added... To prevent this abuse, THDFGroup added something like chunk edge cache -- or similar. And many more features -- but only at cost. IMHO you might have to roll your own solution for something like this, but the best is to avoid it all together. 

1. you could set chunk size to 1: gzip compression makes no sense below 10 bytes! But you could repack -- which might be a good option
2. you could modify `h5::append` and maintain it on your own
3. you could try to convince me why I would benefit from the added complexity regarding edge cache problems.

**A robust solution is:**
- record data to multiple locations: zeromq, .. (this is what I do with stock data)
- buy UPS with big battery
- buy special RAID with battery
- ....

**Comment by m-chichikalov** [comment]
@steven-varga  Thank you Steve.

I found why the calling `flush()` is not safe. It's using condition `if( n == 0 ) return;` to not proceed but does not set `n` to 0 after flush is done.  And when object goes out of scope the flush() calls second time.

About why I called flush(): 
As I described in another issue I'm reusing `h5::pt_t` field in my logger class by rolling the next dataset on the time frame base. I do it because the system generate sample with random sample rate (almost randomly in the time domain), so to be able more quickly access later at specific time interval... Probably I'm describing not clearly :)

And because the move assignment doesn't properly handle destruction of old object I called flush()

Maybe better solution would be to add flash() into move assignment? (see below)

the snippet below to show the issue
``` c++
namespace mc {
	namespace logger {
		struct data_t {
			std::uint64_t t;
			double d0;
			double d1;
		};
	} // logger
} // mc

#include <h5cpp/core>
    namespace h5{
        //template specialization of mc::logger::trade_t to create HDF5 COMPOUND type
        template<> hid_t inline register_struct<mc::logger::data_t>(){

            hid_t ct_00 = H5Tcreate(H5T_COMPOUND, sizeof (mc::logger::data_t));
            H5Tinsert(ct_00, "t_stamp",  HOFFSET(mc::logger::data_t,t),  H5T_NATIVE_UINT64);
            H5Tinsert(ct_00, "delta0",   HOFFSET(mc::logger::data_t,d0), H5T_NATIVE_DOUBLE);
            H5Tinsert(ct_00, "delta1",   HOFFSET(mc::logger::data_t,d1), H5T_NATIVE_DOUBLE);

            //if not used with h5cpp framework, but as a standalone code generator then
            //the returned 'hid_t ct_00' must be closed: H5Tclose(ct_00);
            return ct_00;
        };
    }
    H5CPP_REGISTER_STRUCT(mc::logger::data_t);
#include <h5cpp/io>

TEST_CASE("logger_2", "[h5_logger_2]")
{
    mc::logger::data_t data{ 150345634563456, 0.0000034, 0.0030045 };

    h5::fd_t fd = h5::create( "temp.h5", H5F_ACC_TRUNC );
    h5::pt_t pt = h5::create<mc::logger::data_t>( fd, "dataset_1",
            h5::max_dims{ H5S_UNLIMITED }, h5::chunk{ 5 } | h5::gzip{ 9 });

    // first timeframe
    h5::append( pt, data );
    h5::append( pt, data );
    h5::append( pt, data );
    h5::append( pt, data );

    // after timeframe over creating next dataset by reusing the pt_t object
    pt = h5::create<mc::logger::data_t>( fd, "dataset_2",
        h5::max_dims{ H5S_UNLIMITED }, h5::chunk{ 5 } | h5::gzip{ 9 });

    h5::append( pt, data );
    h5::append( pt, data );
    h5::append( pt, data );
}
```

as a result the first 4 append wouldn't appear in dataset_1 and dataset_2 would contain the last 3 as correct + 4 as a garbage. 
```
HDF5 "temp.h5" {
GROUP "/" {
   DATASET "dataset_1" {
      DATATYPE  H5T_COMPOUND {
         H5T_STD_U64LE "t_stamp";
         H5T_IEEE_F64LE "delta0";
         H5T_IEEE_F64LE "delta1";
      }
      DATASPACE  SIMPLE { ( 0 ) / ( H5S_UNLIMITED ) }
      DATA {
      }
   }
   DATASET "dataset_2" {
      DATATYPE  H5T_COMPOUND {
         H5T_STD_U64LE "t_stamp";
         H5T_IEEE_F64LE "delta0";
         H5T_IEEE_F64LE "delta1";
      }
      DATASPACE  SIMPLE { ( 7 ) / ( H5S_UNLIMITED ) }
      DATA {
      (0): {
            94891369327376,
            4.68825e-310,
            0
         },
      (1): {
            94891369270864,
            4.68826e-310,
            4.68826e-310
         },
      (2): {
            0,
            1.70886e+214,
            9.56525e-315
         },
      (3): {
            94891369327392,
            1.38338e-322,
            1.38338e-322
         },
      (4): {
            150345634563456,
            3.4e-06,
            0.0030045
         },
      (5): {
            150345634563456,
            3.4e-06,
            0.0030045
         },
      (6): {
            150345634563456,
            3.4e-06,
            0.0030045
         }
      }
   }
}
}
```

I've tried to call destructor explicitly before creating the next dataset and got another error when object goes out of scope
```
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: H5Dio.c line 391 in H5Dwrite_chunk(): dxpl_id is not a dataset transfer property list ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Pint.c line 3772 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
```

it's fixed if add destruction actions into move assignment like below
``` C++
pt_t& operator=( h5::pt_t&& pt ){
			if( h5::is_valid( this->ds )) {
				flush();
				free(this->fill_value);
			}
			init(pt.ds);
			return pt;
}
``` 
What do you think?

Regards, Max

**Comment by m-chichikalov** [comment]
There is a snippet to reproduce issue with appending data into reopened dataset

```c++
namespace mc {
	namespace logger {
		struct data_t {
			std::uint64_t t;
			double d0;
			double d1;
		};
	} // logger
} // mc

#include <h5cpp/core>
    namespace h5{
        //template specialization of mc::logger::trade_t to create HDF5 COMPOUND type
        template<> hid_t inline register_struct<mc::logger::data_t>(){

            hid_t ct_00 = H5Tcreate(H5T_COMPOUND, sizeof (mc::logger::data_t));
            H5Tinsert(ct_00, "t_stamp",  HOFFSET(mc::logger::data_t,t),  H5T_NATIVE_UINT64);
            H5Tinsert(ct_00, "delta0",   HOFFSET(mc::logger::data_t,d0), H5T_NATIVE_DOUBLE);
            H5Tinsert(ct_00, "delta1",   HOFFSET(mc::logger::data_t,d1), H5T_NATIVE_DOUBLE);

            //if not used with h5cpp framework, but as a standalone code generator then
            //the returned 'hid_t ct_00' must be closed: H5Tclose(ct_00);
            return ct_00;
        };
    }
    H5CPP_REGISTER_STRUCT(mc::logger::data_t);
#include <h5cpp/io>

TEST_CASE("logger_1", "[h5_logger_1]")
{
    mc::logger::data_t data{ 150345634563456, 0.0000034, 0.0030045 };
    h5::fd_t fd = h5::create( "temp.h5", H5F_ACC_TRUNC );

    {
        h5::pt_t pt = h5::create<mc::logger::data_t>( fd, "dataset_1",
                        h5::max_dims{ H5S_UNLIMITED }, h5::chunk{ 3 } | h5::gzip{ 9 });

        h5::append( pt, data );
        h5::append( pt, data );
        h5::append( pt, data );
        h5::append( pt, data );
        h5::append( pt, data );
        // h5::append( pt, data );
    }

    h5::pt_t pt = h5::open( fd, "dataset_1");

    h5::append( pt, data );
    h5::append( pt, data );
    h5::append( pt, data );
}
```

You will get next error
```
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: H5Dio.c line 400 in H5Dwrite_chunk(): failure to copy offset array
    major: Dataset
    minor: Can't allocate space
  #001: H5Dio.c line 120 in H5D__get_offset_copy(): offset doesn't fall on chunks's boundary
    major: Dataspace
    minor: Inappropriate type
```

if uncomment 6th append(), the number of samples will be even to chunk size and error will gone.

Regards, Max

**Comment by m-chichikalov** [comment]
Ups, didn't see your replays, sorry...

**Comment by steven-varga** [comment]
No worries, can you please check if you like the current state?  I just compiled and ran your code,  and it did the right thing...

**Comment by m-chichikalov** [comment]
> No worries, can you please check if you like the current state? I just compiled and ran your code, and it did the right thing...

@steven-varga replied [here](https://github.com/steven-varga/h5cpp/issues/65#issuecomment-624671350)

**Comment by steven-varga** [comment]
`h5::flush(h5::pt_t& pt );`  will give warning, and `h5::pt_t.flush()` marked as private member. 
**Note:** it is possible to efficiently flush the `h5::pt_t` and will reopen this case  later on. One possible solution is to rewrite/flush the same chunk from time to time, then flush the HDF5 internal caches. 
**caveat:** HDF5 is not a journalling file-system, has no concept of transactions, therefore implementing ACID is tedious.
Will discuss this case with The HDFGroup...
