### ISSUE TITLE
h5cpp.org is down

### ISSUE THREAD

**Issue by kosiu** [steven-varga/h5cpp#68]
I know, it's not right place, It just to let you know that h5cpp.org is down,
I would like to download your "pre-compiler" as deb but I can't.

**Comment by steven-varga** [comment]
Thanks letting me know, AWS temporary evicted the instance -- which I haven't backed up for some time, my bad. It is back and live now, however I only could upload the debian [libh5cpp_1.10.4.6-orig.tar.gz] from this laptop (http://h5cpp.org/download/libh5cpp_1.10.4.6.orig.tar.gz) as I am away from work. Will do the re-upload tonight by sometime 21:00EDT
