### ISSUE TITLE
Help on serializing Eigen::Array< double, Eigen::Dynamic, 3, Eigen::RowMajor >

### ISSUE THREAD

**Issue by Gjacquenot** [steven-varga/h5cpp#7]
Hello @steven-varga ,

I would like to serialize the following Eigen array, with specific number of columns and memory layout. From a quick read of documentation, I thought the following would work. But compilation log is full of errors. After a careful reading, I see that this king of array is not directly supported. Do I have to go to raw data pointer to serialize my array?

    typedef Eigen::Array< double, Eigen::Dynamic, 3, Eigen::RowMajor > ArrayX3D;
    ArrayX3D res2 = ArrayX3D::Zero(10, 3);
    h5::write(fd, "/res",  res2);

Below is my test program

    #include <Eigen/Dense>
    typedef Eigen::Array< double, Eigen::Dynamic, 1 > ArrayXD;
    typedef Eigen::Array< double, Eigen::Dynamic, 3, Eigen::RowMajor > ArrayX3D;
    #include <h5cpp/all>

    int main()
    {
        ArrayXD res = ArrayXD::Zero(10);
        h5::fd_t fd = h5::create("eigen.h5",H5F_ACC_TRUNC);
        h5::write(fd, "/res",  res);
        ArrayX3D res2 = ArrayX3D::Zero(10, 3);
        h5::write(fd, "/res2",  res2);
        // auto ds_3 = h5::create<double>(fd,"/type/short max_dims", h5::max_dims{res2.rows(),3});
        // h5::write(fd, "/res2",  res2,h5::current_dims{res2.rows(),3});
    }

**Comment by steven-varga** [comment]
The code looks ok, should work. Try to check out a previous version 
of H5CPP  from august and see if that solves it? 
Also if you could let me know the dependencies: eigen + hdf5 capi the latter should be installed from source using the most recent branch with version 1.10 api ENABLED. 
( am working on the back port but won't be ready for a month)

Let me know if thus solved the problem, if not tonight will fix it so you can have it tomorrow.
Steve

**Comment by Gjacquenot** [comment]
With gcc 8.2.0, eigen 3.3.5 and latest hdf5, I got an equivalent error message.

    [ 50%] Building CXX object CMakeFiles/demo_h5cpp.dir/demo_h5cpp.cpp.o
    In file included from /pouet/h5cpp/h5cpp/io:14,
                    from /pouet/h5cpp/h5cpp/all:9,
                    from /pouet/demo_h5cpp.cpp:4:
    /pouet/h5cpp/h5cpp/H5Dwrite.hpp: In instantiation of 'h5::herr_t h5::write(const fd_t&, const string&, const T&, args_t&& ...) [
    with T = Eigen::Array<double, -1, 3, 1>; args_t = {}; h5::herr_t = int; h5::fd_t = h5::impl::detail::hid_t<h5::impl::fd_t, H5Fcl
    ose, true, true, false, false>; std::__cxx11::string = std::__cxx11::basic_string<char>]':
    /pouet/demo_h5cpp.cpp:12:32:   required from here
    /pouet/h5cpp/h5cpp/H5Dwrite.hpp:143:7: error: incomplete type 'h5::utils::base<Eigen::Array<double, -1, 3, 1> >' used in nested
    name specifier
    int rank = utils::base<T>::rank;
        ^~~~
    /pouet/h5cpp/h5cpp/H5Dwrite.hpp:145:50: error: invalid use of incomplete type 'struct h5::utils::base<Eigen::Array<double, -1, 3
    , 1> >'
    using element_t = typename utils::base<T>::type;
                                                    ^
    In file included from /pouet/h5cpp/h5cpp/core:33,
                    from /pouet/h5cpp/h5cpp/all:8,
                    from /pouet/demo_h5cpp.cpp:4:
    /pouet/h5cpp/h5cpp/H5Mall.hpp:11:31: note: declaration of 'struct h5::utils::base<Eigen::Array<double, -1, 3, 1> >'
    template<typename T> struct base;
                                ^~~~
    In file included from /pouet/h5cpp/h5cpp/io:14,
                    from /pouet/h5cpp/h5cpp/all:9,
                    from /pouet/demo_h5cpp.cpp:4:
    /pouet/h5cpp/h5cpp/H5Dwrite.hpp:147:39: error: call of overloaded 'get_count(const Eigen::Array<double, -1, 3, 1>&)' is ambiguous
    h5::count_t count = utils::get_count( ref );
                        ~~~~~~~~~~~~~~~~^~~~~~~
    In file included from /pouet/h5cpp/h5cpp/H5Mall.hpp:32,
                    from /pouet/h5cpp/h5cpp/core:33,
                    from /pouet/h5cpp/h5cpp/all:8,
                    from /pouet/demo_h5cpp.cpp:4:
    /pouet/h5cpp/h5cpp/H5Mall.hpp:58:2: note: candidate: 'h5::count_t h5::utils::get_count(eigen::rowvec<unsigned char>&)'
    H5CPP_REGISTER_TYPE(unsigned char, H5T_NATIVE_UCHAR)    H5CPP_REGISTER_TYPE(char, H5T_NATIVE_CHAR)
    ^~~~~~~~~~~~~~~~~~~
    /pouet/h5cpp/h5cpp/H5Mall.hpp:58:2: note: candidate: 'h5::count_t h5::utils::get_count(eigen::colvec<unsigned char>&)'
    H5CPP_REGISTER_TYPE(unsigned char, H5T_NATIVE_UCHAR)    H5CPP_REGISTER_TYPE(char, H5T_NATIVE_CHAR)
    ^~~~~~~~~~~~~~~~~~~
    /pouet/h5cpp/h5cpp/H5Mall.hpp:58:2: note: candidate: 'h5::count_t h5::utils::get_count(eigen::mat<unsigned char>&)'
    H5CPP_REGISTER_TYPE(unsigned char, H5T_NATIVE_UCHAR)    H5CPP_REGISTER_TYPE(char, H5T_NATIVE_CHAR)
    ^~~~~~~~~~~~~~~~~~~
    /pouet/h5cpp/h5cpp/H5Mall.hpp:58:2: note: candidate: 'h5::count_t h5::utils::get_count(eigen::arowvec<unsigned char>&)'
    H5CPP_REGISTER_TYPE(unsigned char, H5T_NATIVE_UCHAR)    H5CPP_REGISTER_TYPE(char, H5T_NATIVE_CHAR)
    ^~~~~~~~~~~~~~~~~~~
    /pouet/h5cpp/h5cpp/H5Mall.hpp:58:2: note: candidate: 'h5::count_t h5::utils::get_count(eigen::acolvec<unsigned char>&)'
    H5CPP_REGISTER_TYPE(unsigned char, H5T_NATIVE_UCHAR)    H5CPP_REGISTER_TYPE(char, H5T_NATIVE_CHAR)

**Comment by steven-varga** [comment]
commit: **f1b9f49**
Guillaume,

I added the missing compile time templates updo 4 dimensions for both Arrays and Matrices; In addition to Row and Col major distinction. However didn't have time to verify if the stored data is in the correct order nor did I verify READ. 
Perhaps you could pitch in and let me know if I got it right? Any dimensions flipped? etc...

As of C++11: it is not tested, the aim was to get it to c++14. Few days ago I noticed 'if constexpr ( .. ){}' hanging around, which could/will break c++11. Expect this corrected in a month or so because of MPI + attributes and error handling being added. 

One more thing: because I mostly work with armadillo, if I left something out of Eigen and you think it is used rather often file a ticket and will look into it. Keep in mind though there is not way to support all features of all linalg systems without community involved 

best wishes,
steve

**Comment by Gjacquenot** [comment]
That was fast...

It now works.  I see that you instantiated lots of Eigen stuff. 
The following example now works. I manually checked the content of the generated array.

    #include <Eigen/Dense>
    typedef Eigen::Array< double, Eigen::Dynamic, 3, Eigen::RowMajor > ArrayX3D;
    #include <h5cpp/all>

    int main()
    {
        h5::fd_t fd = h5::create("eigen.h5",H5F_ACC_TRUNC);
        ArrayX3D res = ArrayX3D::Zero(10, 3);
        for (size_t i=0;i<10;++i) res.row(i) << 3*i, 3*i+1, 3*i+2;
        h5::write(fd, "/res",  res);
    }

**Comment by Gjacquenot** [comment]
I will propose you a google test for eigen array and matrices and close issue.

**Comment by steven-varga** [comment]
Thanks!

You see the **static/compile time size is not supported**  in this phase; in a different review -- sometime in the next year -- will make the adjustments so those instatiations which leverage the differences, are not needed. While Eigen is a popular choice, there are many other systems,  used on super computers -- which are being studied.  Once the most common denominator is identified, and those systems are integrated then I can make the refined version which addresses this 'unnecessary boilerplate' you've noticed.

Don't forget to  check out the partial IO, which makes this operation less likely. In addition there is build in mechanism that grabs the size of the array and IO calls will do the right thing: saving your matrix into HDF5 container and using it in some other system.

steve
